//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wastearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OtpHistory
    {
        public long Id { get; set; }
        public string ContactNumber { get; set; }
        public string Otp { get; set; }
        public Nullable<bool> IsVerified { get; set; }
        public Nullable<System.DateTime> OtpExpired { get; set; }
        public Nullable<System.DateTime> VerifiedTime { get; set; }
    }
}
