//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wastearn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Request
    {
        public long id { get; set; }
        public long residentid { get; set; }
        public Nullable<System.DateTime> requestedOn { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> completedOn { get; set; }
        public Nullable<byte> completedBy { get; set; }
        public string feedback { get; set; }
        public Nullable<decimal> rating { get; set; }
        public Nullable<decimal> weight { get; set; }
    }
}
